const Phonedata = [
  {
    device: 'phone',
    title: 'iPhone 14 Pro Max',
    desc: "iPhone 14 Pro Max has a 6.7-inch1 all-screen Super Retina XDR display. The back is premium matte glass, and there's a flat-edge stainless steel band around the frame. The side button is on the right side of the device. There are three cameras on the back: Ultra Wide, Main, and Telephoto. There's a LiDAR Scanner on the back. There's an LED True Tone flash on the back. In the United States, there is no SIM tray. In other countries or regions, there's a SIM tray on the left side that holds a \"fourth form factor\" (4FF) nano-SIM card.",
    img: [
      'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-14-pro-max-colors.png',
      '/assets/red.jpg',
      '/assets/gold.png',
      '/assets/rosegold.png',
      '/assets/silver.jpg',
    ],
    alt: 'iPhone 14 Pro Max',
    categories: [
      {
        color: ['Silver', 'gold', 'space black', 'deep purple'],
      },
    ],
    size: '128 GB, 256 GB, 512 GB, 1 TB',
    price: 1099,
    discountPrice: 1000,
  },
  {
    device: 'phone',
    title: 'iPhone 14 Pro',
    desc: "iPhone 14 Pro has a 6.1-inch1 all-screen Super Retina XDR display. The back is premium matte glass, and there's a flat-edge stainless steel band around the frame. The side button is on the right side of the device. There are three cameras on the back: Ultra Wide, Main, and Telephoto. There's a LiDAR Scanner on the back. There's an LED True Tone flash on the back. In the United States, there is no SIM tray. In other countries or regions, there's a SIM tray on the left side that holds a \"fourth form factor\" (4FF) nano-SIM card..",
    img: [
      'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-14-pro-colors.png',
      '/assets/red.jpg',
      '/assets/gold.png',
      '/assets/rosegold.png',
      '/assets/silver.jpg',
    ],
    alt: 'iPhone 14 Pro',
    categories: [
      {
        color: ['Silver', 'gold', 'space black', 'deep purple'],
      },
    ],
    size: '128 GB, 256 GB, 512 GB, 1 TB',
    price: 1099,
    discountPrice: 999,
  },
  {
    device: 'phone',
    title: 'iPhone 14 Plus',
    desc: 'The iPhone 14 Plus has a 6.7 inch1 all-screen Super Retina XDR display. The back is glass, and there\'s a flat-edged anodized aluminum band around the frame. The side button is on the right side of the device. There are two cameras on the back: Ultra Wide and Main. In the United States, there is no SIM tray. In other countries or regions, there\'s a SIM tray on the left side that holds a "fourth form factor" (4FF) nano-SIM card.',
    img: [
      'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-14-plus-colors.png',
      '/assets/red.jpg',
      '/assets/gold.png',
      '/assets/rosegold.png',
      '/assets/silver.jpg',
    ],
    alt: 'iPhone 14 Plus',
    categories: [
      {
        color: ['Silver', 'gold', 'space black', 'deep purple'],
      },
    ],
    size: '128 GB, 256 GB, 512 GB, 1 TB',
    price: 899,
    discountPrice: 850,
  },
  {
    device: 'phone',
    title: 'iPhone 14',
    desc: ' The iPhone 14 has a 6.1 inch1 all-screen Super Retina XDR display. The back is glass, and there\'s a flat-edged anodized aluminum band around the frame. The side button is on the right side of the device. There are two cameras on the back: Ultra Wide and Main. In the United States, there is no SIM tray. In other countries or regions, there\'s a SIM tray on the left side that holds a "fourth form factor" (4FF) nano-SIM card.',
    img: [
      'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iphone/iphone-14-colors.png',
      '/assets/red.jpg',
      '/assets/gold.png',
      '/assets/rosegold.png',
      '/assets/silver.jpg',
    ],
    alt: 'iPhone 14',
    categories: [
      {
        color: ['Silver', 'gold', 'space black', 'deep purple'],
      },
    ],
    size: '128 GB, 256 GB, 512 GB, 1 TB',
    price: 1099,
    discountPrice: 1000,
  },
{
  device: 'phone',
  title: 'iPhone SE',
  desc:'It features the Apple A15 processor and 5G support in the same external form factor as the iPhone 8 / 2nd-generation SE. It uses stronger glass like that from the back of the iPhone 13 series — though it was promoted as the "toughest glass in a smartphone", it was not identified as Ceramic Shield.[1][2] It uses the same 12 megapixel rear camera as the previous generation SE, but the A15 processor improves image computation support. It is also the last iPhone model to still use Touch ID.',
  img: [
    'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-se-storage-select-202207-midnight?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1655312146228',
    'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-se-finish-select-202207-product-red?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1655316263304',
    'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-se-finish-select-202207-starlight?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1655316263356',
    '/assets/red.jpg',
    '/assets/white.png',
    '/assets/black.png',
  ],
  alt:'iPhone SE',
  categories: [
    {
      color: ['white', 'black', 'red'],
    },
  ],
  size: '64, 128, 256 GB',
  price: 429,
  discountPrice: 400,
  },
  {
  device: 'phone',
  title: 'iPhone 13 pro max',
  desc: ' it is powered by the six-core Apple A15 processor, but with the addition of a 5th GPU core. It is splash, water, and dust resistant.[2] It supports 5G networks for improved speed (up to 4Gbps) with the ability to automatically switch to LTE as needed to conserve battery life. The wireless changing coil inside the phone includes MagSafe for magnetic alignment and attachment of chargers and accessories. The Lightning connector supports faster charging though USB-C.The Pro version features a rear-facing triple camera system vs. dual in standard models with ultra wide, wide, and telephoto lens, along with a LiDAR sensor for recording distance.',
  img: [
    'https://www.91-img.com/gallery_images_uploads/5/5/559d300a0d640fe6ee59f4b4bb359ddf4a914777.jpg?tr=h-550,w-0,c-at_max',
    'https://www.91-img.com/gallery_images_uploads/b/b/bb554515f0d88d04c0bda506d9df1bede5ca7b3f.jpg?tr=h-550,w-0,c-at_max',
    'https://www.91-img.com/gallery_images_uploads/5/8/58dbfe1f7eb62456e4d14c4dd6db2eb0f529bf4e.jpg?tr=h-550,w-0,c-at_max',
    'https://www.91-img.com/gallery_images_uploads/9/c/9ce00564ce385a05d9a091d4359d07853ce060b0.jpg?tr=h-550,w-0,c-at_max',
     '/assets/graphite.jpg',
    '/assets/silver.png',
    '/assets/gold.png',
    '/assets/sierrablue.png',
    '/assets/alpinegreen.jpg',
  ],
  alt: 'iPhone 13 pro max',
  categories: [
    {
      color: ['graphite', 'silver', 'gold','sierra blue','alpine green'],
    },
  ],
  size: '64, 128, 256 GB, 1 TB',
  price: 1099,
  discountPrice: 1000. 
  },
  {
  device: 'phone',
      title: 'iPhone 13 pro',
      desc: ' it is powered by the six-core Apple A15 processor, but with the addition of a 5th GPU core. It is splash, water, and dust resistant. It supports 5G networks for improved speed (up to 4Gbps) with the ability to automatically switch to LTE as needed to conserve battery life. The wireless changing coil inside the phone includes MagSafe for magnetic alignment and attachment of chargers and accessories. The Lightning connector supports faster charging though USB-C',
     img: [
      'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-5.jpg',
      'https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-01.jpg',
       '/assets/silver.jpg',
        '/assets/gold.png',
        '/assets/graphite.jpg',
        '/assets/sierrablue.png',
      ],
      alt: 'iPhone 13 pro',
      categories: [
        {
          color: ['Sierra blue', '', 'silver', 'gold', 'graphite'],
        },
      ],
      size: '128 GB, 256 GB, 512 GB, 1 TB',
      price: 999,
      discountPrice: 979,
    },
    {
      device: 'phone',
      title: 'iPhone 13 mini',
      desc: 'the 13 mini is powered by the six-core Apple A15 Bionic processor and features Ceramic Shield on the front screen and back panel. It is splash, water, and dust resistant. It supports 5G networks for improved speed (up to 4Gbps) with the ability to automatically switch to LTE as needed to conserve battery life. The wireless changing coil inside the phone includes MagSafe for magnetic alignment and attachment of chargers and accessories. The Lightning connector supports faster charging though USB-C',
       img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-storage-select-202207-5-4inch-product-red?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1654896888053',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-5-4inch-blue?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1656713272198',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-5-4inch-pink?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1656713272059',
       'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-5-4inch-midnight?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1656713272020',
       'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-5-4inch-starlight?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1656713272724',
        '/assets/starlightwhite.jpg',
        '/assets/midnightblack.jpg',
        '/assets/blue.jpg',
        '/assets/pink.jpg',
        '/assets/red.jpg',
      ],
      alt: 'iPhone 13 mini',
      categories: [
        {
          color: ['starlight white', 'midnight black', 'blue', 'pink', 'red'],
        },
      ],
      size: '128 GB, 256 GB, 512 GB',
      price: 699,
      discountPrice: 670,
    },
    {
      device: 'phone',
      title: 'iPhone 13',
      desc: 'it is powered by the six-core Apple A15 Bionic processor and features Ceramic Shield on the front screen and back panel. It is splash, water, and dust resistant. It supports 5G networks for improved speed (up to 4Gbps) with the ability to automatically switch to LTE as needed to conserve battery life. The wireless changing coil inside the phone includes MagSafe for magnetic alignment and attachment of chargers and accessories. The Lightning connector supports faster charging though USB-C.',
      img: [ 
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-6-1inch-starlight?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1656712888655',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-6-1inch-midnight?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1656712887881',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-6-1inch-blue?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1656712888128',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-6-1inch-pink?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1657641867367',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-finish-select-202207-6-1inch-product-red?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1656720518797',
        '/assets/starlightwhite.jpg',
        '/assets/midnightblack.png',
        '/assets/blue.png',
        '/assets/pink.jpg',
        '/assets/red.png',
      ],
      alt: 'iPhone 13',
      categories: [
        {
          color: ['Starlight white', 'midnight black', 'blue', 'pink', 'red'],
        },
      ],
      size: '128 GB, 256 GB, 512 GB,',
      price: 788,
      discountPrice: 768,
    },
    {
      device: 'phone',
      title: 'iPhone 12 pro max',
      desc: " it is powered by the six-core Apple A14 processor and features Ceramic Shield on the front screen and back panel for 4x improved drop performance over previous models. It supports 5G networks for improved speed (up to 4Gbps) with the ability to automatically switch to LTE as needed to conserve battery life. The wireless changing coil inside the phone includes MagSafe for magnetic alignment and attachment of chargers and accessories. The updated Lightning connector supports faster charging though USB-C.",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-blue?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662149977576',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-purple?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150036753',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-green_AV1_GEO_US?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150004692',
        '/assets/pacificblue.jpg',
        '/assets/gold.png',
        '/assets/graphite.png',
        '/assets/silver.jpg',
      ],
      alt: 'iPhone 12 pro max',
      categories: [
        {
          color: ['pacific blue', 'gold', 'silver', 'graphite'],
        },
      ],
      size: '128 GB, 256 GB, 512 GB',
      price: 1099,
      discountPrice: 1079,
    },
    {
      device: 'phone',
      title: 'iPhone 12 pro',
      desc: "it is powered by the six-core Apple A14 processor and features Ceramic Shield on the front screen and back panel for 4x improved drop performance over previous models. It supports 5G networks for improved speed (up to 4Gbps) with the ability to automatically switch to LTE as needed to conserve battery life. The wireless changing coil inside the phone includes MagSafe for magnetic alignment and attachment of chargers and accessories. The updated Lightning connector supports faster charging though USB-C.",
      img: [
        'https://static.wikia.nocookie.net/ipod/images/1/12/IPhone_12_Pro_Max_back_colors.jpg/revision/latest?cb=20201014073402',
        '/assets/pacificblue.jpg',
        '/assets/gold.png',
        '/assets/graphite.png',
        '/assets/silver.jpg',
      ],
      alt: 'iPhone 12 Pro',
      categories: [
        {
          color: ['pacific blue', 'gold', 'silver', 'graphite'],
        },
      ],
      size: '128 GB, 256 GB, 512 GB',
      price: 999,
      discountPrice: 970,
    },
    {
      device: 'phone',
      title: 'iPhone 12 mini',
      desc: "the 12 mini is powered by the six-core Apple A14 Bionic processor and features Ceramic Shield on the front screen and back panel for 4x improved drop performance over previous models. It supports 5G networks for improved speed (up to 4Gbps) with the ability to automatically switch to LTE as needed to conserve battery life. The wireless changing coil inside the phone includes MagSafe for magnetic alignment and attachment of chargers (up to 12W) and accessories. The updated Lightning connector supports faster charging though USB-C (up to 20W)..",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-blue?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662149977576',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-white?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150115751',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-green?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150005626',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-purple?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150036753',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-black?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662149951953',
        '/assets/blue.jpg',
        '/assets/white.png',
        '/assets/green.png',
        '/assets/purple.jpg',
        '/assets/black.png',
      ],
      alt: 'iPhone 12 mini',
      categories: [
        {
          color: ['blue', 'white', 'green', 'purple','black'],
        },
      ],
      size: '128 GB, 256 GB, 512 GB',
      price: 699,
      discountPrice: 670,
    },
    {
      device: 'phone',
      title: 'iPhone 12',
      desc: " it is powered by the six-core Apple A14 Bionic processor and features Ceramic Shield on the front screen and back panel for 4x improved drop performance over previous models. It supports 5G networks for improved speed (up to 4Gbps) with the ability to automatically switch to LTE as needed to conserve battery life. The wireless changing coil inside the phone includes MagSafe for magnetic alignment and attachment of chargers and accessories. The updated Lightning connector supports faster charging though USB-C.",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-blue?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662149977576',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-white?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150115751',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-green?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150005626',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-purple?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150036753',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-black?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662149951953',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-finish-select-202207-product-red?wid=2560&hei=1440&fmt=p-jpg&qlt=80&.v=1662150081176',
        '/assets/red.jpg',
        '/assets/blue.png',
        '/assets/white.png',
        '/assets/purple.jpg',
        '/assets/green.png',
        '/assets/black.jpg',
      ],
      alt: 'iPhone 12',
      categories: [
        {
          color: ['red', 'blue', 'white', 'purple','green','black'],
        },
      ],
      size: '128 GB, 256 GB, 512 GB,',
      price: 799,
      discountPrice: 799,
    },
    {
      device: 'phone',
      title: 'iPhone 11 Pro max',
      desc: 'The iPhone 11 Pro Max models uses the 13th generation of Apple custom chipset called the Apple A13 Bionic. As of the release date, Apple claimed Apple claimed that this chipset contained the fastest CPU and GPU ever available in a smartphone the iPhone 11 Pro Max were shipped with iOS 13 in 64GB, 256GB and 512GB configurations. Unlike the base iPhone 11 model, the Pro versions included a new triple-lens 12MP rear camera system: a telephoto, wide, and ultra-wide.',
      img: [
        '',
        '/assets/midnightgreen.jpg',
        '/assets/gold.png',
        '/assets/spacegray.png',
        '/assets/silver.jpg',
      ],
      alt: 'iPhone 11 Pro max',
      categories: [
        {
          color: ['Silver', 'gold', 'midnight green', 'space gray'],
        },
      ],
      size: '128 GB, 256 GB, 512 GB',
      price: 1115.93,
      discountPrice: 1100,
    },
    {
      device: 'phone',
      title: 'iPhone 11 pro',
      desc: "The iPhone 11 models use Apple's custom-designed system on a chip (SoC) called the Apple A13 Bionic. As of the release date, Apple claimed that this chipset contained the fastest CPU and GPU ever available in a smartphone the Pro versions include a new triple-lens 12MP rear camera system: a telephoto, wide, and ultra-wide.",
      img: [
        'https://static.wikia.nocookie.net/ipod/images/4/41/Iphone-11-and-11-pro-release-date.jpg/revision/latest?cb=20190910205526',
        '/assets/midnightgreen.jpg',
        '/assets/gold.png',
        '/assets/spacegray.png',
        '/assets/silver.jpg',
      ],
      alt: 'iPhone 11 Pro',
      categories: [
        {
          color: ['midnight green', 'gold', 'space gray', 'slver'],
        },
      ],
      size: '64 GB, 256 GB, 512 GB,',
      price: 1099,
      discountPrice: 1060,
    },
    {
      device: 'phone',
      title: 'iPhone 11',
      desc: "The iPhone 11 uses the 13th generation of Apple's custom chipset called the Apple A13 Bionic.Apple claimed that this chipset contained the fastest CPU and GPU available in a smartphone at the time. The phone was available in 64, 128, and 256 GB configurations Apple claimed the iPhone 11 battery will last an hour longer than the battery in the iPhone XR and XS Max.",
      img: [
        '',
        '/assets/red.jpg',
        '/assets/black.png',
        '/assets/white.png',
        '/assets/yellow.jpg',
        '/assets/green.png',
        '/assets/purple.jpg',
      ],
      alt: 'iPhone 11',
      categories: [
        {
          color: ['red', 'black', 'white', 'purple', 'yellow', 'green'],
        },
      ],
      size: '64 GB, 128 GB, 256 GB',
      price: 499,
      discountPrice: 450,
    },
    {
      device: 'phone',
      title: 'iPhone XS',
      desc: "The new features primarily consisted of a new faster 6-core Apple A12 Bionic processor, a 5.8 or 6.5-inch Super Retina display, updated Face ID, and an improved dual-camera system. The XS also adopted a 4x4 MIMO 4G antenna, doubling the maximum cellular bandwidth over that of the 2x2 antennae in the iPhone X and XR the iPhone XS was released with iOS 12 as its first operating system.",
      img: [
        'https://static.wikia.nocookie.net/ipod/images/b/b7/U_10185944.jpg/revision/latest?cb=20200419010802',
        '/assets/black.png',
        '/assets/white.png',
        '/assets/gold.jpg',
      ],
      alt: 'iPhone xs',
      categories: [
        {
          color: ['black', 'white', 'gold'],
        },
      ],
      size: '64 GB, 256 GB, 512 GB',
      price: 1149,
      discountPrice: 1100,
    },
    {
      device: 'phone',
      title: 'iPhone XS max',
      desc: "The features primarily consist of a new faster six core A12 Bionic processor, a 6.5-inch Super Retina display, updated Face ID, and an improved dual-camera system. The XS Max also adopted a 4x4 MIMO 4G antenna, doubling the maximum cellular bandwidth over that of the 2x2 antennae in the iPhone X and XR the iPhone XS Max shipped with iOS 12 as its original operating system and is supported by iOS 16.",
      img: [
        'https://static.wikia.nocookie.net/ipod/images/b/b7/Xsmax.jpg/revision/latest?cb=20200822100154',
        '/assets/gold.png',
        '/assets/gray.png',
        '/assets/silver.jpg',
      ],
      alt: 'iPhone xs max',
      categories: [
        {
          color: ['gold', 'gray', 'silver'],
        },
      ],
      size: '64 GB, 256 GB, 512 GB',
      price: 530,
      discountPrice: 500,
    },
    {
      device: 'phone',
      title: 'iPhone XR',
      desc: "Cost-cutting was made possible through the use of a more conventional LCD Liquid Retina display instead of an OLED-based Super Retina HD display. Instead of dual rear-facing cameras like the iPhone X and XS, the XR had only one rear-facing camera.[1][2] The XR also uses a 2x2 MIMO 4G antenna, like the preceding iPhone X, but with less maximum cellular bandwidth than that of the 4x4 antennae in the more expensive iPhone XS and XS Max.",
      img: [
        'https://static.wikia.nocookie.net/ipod/images/5/58/IPhone_XR_colors.png/revision/latest?cb=20200608212747',
        '/assets/black.png',
        '/assets/white.png',
        '/assets/coral.jpg',
        '/assets/yellow.png',
        '/assets/red.png',
        '/assets/blue.png',
      ],
      alt: 'iPhone XR',
      categories: [
        {
          color: ['black', 'white', 'coral', 'yellow', 'red', 'blue'],
        },
      ],
      size: '64 GB, 128 GB, 256 GB,',
      price: 261,
      discountPrice: 200,
    },  
    {
      device: 'phone',
      title: 'iPhone x',
      desc: "The iPhone X adopted OLED screen technology from Samsung and used a glass and stainless-steel form factor. It offered wireless charging and removed the Home button in favor of a new bezel-less design. It also introduced Face ID – a new type of password authentication using advanced technologies to scan the user's face to unlock the device. Animoji (Animated emoji) was also introduced with the iPhone X. It shipped with iOS 11 and is powered by the Apple A11 Bionic processor. It came in 64 and 256 GB storage capacities The iPhone X was met with mixed reception - it received universal praise for its display, camera, and build quality. However, the sensor housing notch at the top of the screen was heavily mocked by users, but later adopted by many other smartphone companies in various implementations..",
      img: [
        'https://static.wikia.nocookie.net/ipod/images/f/ff/Space_Gray_iPhone_X_Rear.png/revision/latest?cb=20171120004546',
        '/assets/spacegray.png',
        '/assets/silver.jpg',
      ],
      alt: 'iPhone x',
      categories: [
        {
          color: ['space gray', 'silver'],
        },
      ],
      size: '64 GB, 256 GB',
      price: 679,
      discountPrice: 600,
    },
    {
      device: 'phone',
      title: 'iPhone 8 Plus',
      desc: "The iPhone 8 Plus includes a faster Apple A11 Bionic processor, a glass body that is water and dust-resistant and supports wireless charging, louder speakers, a new Retina HD display with True Tone technology, dual 12-megapixel wide and telephoto cameras with more advanced sensors and new color filter with optical image stabilization, and an exclusive Portrait Mode lighting system, previously featured on the iPhone 7 Plus The iPhone 8 and 8 Plus initially came with iOS 11 pre-installed and are now the oldest models still supported by iOS 16.",
      img: [
        'https://static.wikia.nocookie.net/ipod/images/4/47/IPhone_8_Plus.jpg/revision/latest?cb=20200822053553',
        '/assets/silver.jpg',
        '/assets/gold.png',
        '/assets/spacegray.jpg',
      ],
      alt: 'iPhone 8 Plus',
      categories: [
        {
          color: ['silver', 'gold', 'space gray'],
        },
      ],
      size: '64 GB, 128 GB, 256 GB',
      price: 221,
      discountPrice: 200,
    },
    {
      device: 'phone',
      title: 'iPhone 8',
      desc: "The iPhone 8 includes a faster Apple A11 Bionic processor, a glass body that is water and dust-resistant and supports wireless charging, louder speakers, a new Retina display with True Tone technology, dual 12-megapixel wide and telephoto cameras with more advanced sensors and new color filter with optical image stabilization, and an exclusive Portrait Mode lighting system, previously only featured on the iPhone 7 Plus. The iPhone 8 and 8 Plus initially came with iOS 11 pre-installed and are now the oldest models still supported by iOS 16.",
      img: [
        'https://static.wikia.nocookie.net/ipod/images/9/9e/IPhone_8_front.png/revision/latest?cb=20170916232344',
        '/assets/red.jpg',
        '/assets/gold.png',
        '/assets/silver.png',
        '/assets/gray.jpg',
      ],
      alt: 'iPhone 8',
      categories: [
        {
          color: ['red', 'gold', 'silver', 'gray'],
        },
      ],
      size: '64 GB, 128 GB, 256 GB',
      price: 132,
      discountPrice: 100,
    },
    {
      device: 'Ipad',
      title: 'Ipad 10th Generation',
      desc: ".",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-2022-hero-blue-wifi-select?wid=470&hei=556&fmt=png-alpha&.v=1664387252369',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-2022-hero-pink-wifi-select?wid=470&hei=556&fmt=png-alpha&.v=1664387253676',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-2022-hero-silver-wifi-select?wid=470&hei=556&fmt=png-alpha&.v=1664387253665',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-2022-hero-yellow-wifi-select?wid=470&hei=556&fmt=png-alpha&.v=1664387253668',
        '/assets/blue.jpg',
        '/assets/pink.png',
        '/assets/silver.png',
        '/assets/yellow.jpg',
      ],
      alt: 'Ipad 10th Generation',
      categories: [
        {
          color: ['red', 'gold', 'silver', 'gray'],
        },
      ],
      size:  '64 GB, 256 GB',
      price: 499,
      discountPrice: 470,
    },
    {
      device: 'Ipad',
      title: 'Ipad Pro',
      desc: "The 12.9-inch Liquid Retina XDR display was built to deliver extreme brightness, deep blacks and subtle details. It’s perfect for viewing and editing high-brightness and high-contrast content like HDR photos and videos 2732-by-2048 resolution, 5.6 million pixels P3 wide color, True Tone for comfortable viewing, ProMotion adaptive refresh rate, Antireflective coating 1600 nits peak brightness (HDR) 1,000,000:1 contrast ratio.",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-spacegray-202210?wid=470&hei=556&fmt=p-jpg&qlt=95&.v=1664411207157',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-silver-202210?wid=470&hei=556&fmt=p-jpg&qlt=95&.v=1664411207141',
        '/assets/spacegray.jpg',
        '/assets/silver.png',
      ],
      alt: 'Ipad Pro',
      categories: [
        {
          color: ['silver', 'space gray'],
        },
      ],
      size: ' 128 GB, 256 GB, 512 GB, 1TB, 2TB',
      Price: 1899, 
      discountPrice: 1870,
    },  
    {
      device: 'Ipad',
      title: 'Ipad Air',
      desc: " Available space is less and varies due to many factors. A standard configuration uses approximately 12GB to 17GB of space, including iPadOS 15 with its latest features and Apple apps that can be deleted. Apple apps that can be deleted use about 4.5GB of space, and you can download them back from the App Store. Storage capacity subject to change based on software version, settings, and iPad model..",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-select-wifi-spacegray-202203?wid=470&hei=556&fmt=png-alpha&.v=1645066742664',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-select-wifi-blue-202203?wid=470&hei=556&fmt=png-alpha&.v=1645065732688',
  'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-select-wifi-pink-202203?wid=470&hei=556&fmt=png-alpha&.v=1645066399526',
  'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-select-wifi-purple-202203?wid=470&hei=556&fmt=png-alpha&.v=1645066730601',
  'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-select-wifi-starlight-202203?wid=470&hei=556&fmt=png-alpha&.v=1645895139236',
        '/assets/spacegray.png',
        '/assets/blue.png',
        '/assets/pink.png',
        '/assets/purple.png',
        '/assets/starlight.png',
      ],
      alt: 'Ipad Air',
      categories: [
        {
          color: ['space gray','blue','pink','purple', 'starlight'],
        },
      ],
      size: '64GB,256 GB',
      price: 1899 ,
      discountPrice: 1870,
    },  
    {
      device: 'Airpods',
      title: 'Airpod 2nd Generation',
      desc: ".",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV7N2?wid=1000&hei=1000&fmt=jpeg&qlt=95&.v=1551489688005',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV7N2_AV1?wid=1000&hei=1000&fmt=jpeg&qlt=95&.v=1551489684370',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MV7N2_AV3?wid=1000&hei=1000&fmt=jpeg&qlt=95&.v=1552508263186',
        '/assets/white.jpg',
      ],
      alt: 'Airpod 2nd Grneraton',
      categories: [
        {
          color: ['white'],
        },
      ],
      price:129 ,
      discountPrice: 100,
    },  
    {
      device: 'Airpod',
      title: 'Airpod 3rd Generation',
      desc: ".",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-spacegray-202210?wid=470&hei=556&fmt=p-jpg&qlt=95&.v=1664411207157',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-silver-202210?wid=470&hei=556&fmt=p-jpg&qlt=95&.v=1664411207141',
        '/assets/spacegray.jpg',
        '/assets/silver.png',
      ],
      alt: 'Ipad Pro',
      categories: [
        {
          color: ['silver', 'space gray'],
        },
      ],
      size: '128 GB,256 GB, 512 GB, 1TB,2TB',
      price:1899 ,
      discountPrice: 1870,
    },  
    {
      device: 'Ipad',
      title: 'Ipad Pro',
      desc: "The 12.9-inch Liquid Retina XDR display was built to deliver extreme brightness, deep blacks and subtle details. It’s perfect for viewing and editing high-brightness and high-contrast content like HDR photos and videos 2732-by-2048 resolution, 5.6 million pixels P3 wide color, True Tone for comfortable viewing, ProMotion adaptive refresh rate, Antireflective coating 1600 nits peak brightness (HDR) 1,000,000:1 contrast ratio.",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-spacegray-202210?wid=470&hei=556&fmt=p-jpg&qlt=95&.v=1664411207157',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-silver-202210?wid=470&hei=556&fmt=p-jpg&qlt=95&.v=1664411207141',
        '/assets/spacegray.jpg',
        '/assets/silver.png',
      ],
      alt: 'Ipad Pro',
      categories: [
        {
          color: ['silver', 'space gray'],
        },
      ],
      size: '128 GB,256 GB, 512 GB, 1TB,2TB',
      price: 1899,
      discountPrice: 1870,
    },  
    {
      device: 'Ipad',
      title: 'Ipad Pro',
      desc: "The 12.9-inch Liquid Retina XDR display was built to deliver extreme brightness, deep blacks and subtle details. It’s perfect for viewing and editing high-brightness and high-contrast content like HDR photos and videos 2732-by-2048 resolution, 5.6 million pixels P3 wide color, True Tone for comfortable viewing, ProMotion adaptive refresh rate, Antireflective coating 1600 nits peak brightness (HDR) 1,000,000:1 contrast ratio.",
      img: [
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-spacegray-202210?wid=470&hei=556&fmt=p-jpg&qlt=95&.v=1664411207157',
        'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-pro-11-select-wifi-silver-202210?wid=470&hei=556&fmt=p-jpg&qlt=95&.v=1664411207141',
        '/assets/spacegray.jpg',
        '/assets/silver.png',
      ],
      alt: 'Ipad Pro',
      categories: [
        {
          color: ['silver', 'space gray'],
        },
      ],
      size: '128 GB,256 GB, 512 GB, 1TB,2TB',
      price:1899 ,
      discountPrice: 1870,
    },  
  module.exports = Phonedata ]
